services:
  web:
    image: hufsmeals/server
    container_name: web
    command: bash -c "
      while ! nc -z mysql_db 3306; do sleep 1; done && python manage.py makemigrations && python manage.py migrate && gunicorn MoC.wsgi:application -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    restart: always
    networks:
      - server
    depends_on:
      - mysql_db

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./static:/static
      - ./media:/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always
    networks:
      - server
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 'wjdtjq98'
      MYSQL_DATABASE: 'hufsmeals'
      MYSQL_USER: 'worker'
      MYSQL_PASSWORD: 'wjdtjq98'
    volumes:
      - database:/var/lib/mysql
    restart: always
    ports:
      - "3305:3306"
    networks:
      - server

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - server
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  server:
    driver: bridge

volumes:
  database:
